
dir_path = "/gpfs/milgram/pi/chang/pg496/data_dir/social_gaze/social_gaze_eyetracking/rois";
mat_files = dir( fullfile(dir_path, "*.mat") );

rois_of_interest = { ...
    "face", ...
    "eyes_nf", ...
    "mouth", ...
    "left_nonsocial_object", ...
    "right_nonsocial_object" ...
};
for i = 1:numel(mat_files)
    f_name = mat_files(i).name;
    roi_struct = load( fullfile( dir_path, f_name ) );
    roi_struct = roi_struct.var;
    
end